### PR TITLE
call rubocop with --parallel

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
why do we have the `rake` variant anyway? it's so slow…

```
bundle exec rubocop --parallel  168.75s user 1.86s system 549% cpu 31.020 total
bundle exec rubocop  79.55s user 0.76s system 99% cpu 1:20.87 total
bundle exec rake rubocop  71.61s user 0.88s system 99% cpu 1:12.84 total
```

**Comment by ekohl** [comment]
> why do we have the `rake` variant anyway? it's so slow…

My idea behind it was that you could customize invocation there. For example, detect the GH CI env and add the correct formatter. I didn't realize it was so slow, but that's probably because I'm used to Puppet environments where it doesn't have to load Rails (and half the world).

Once all plugins at least have a non-ancient RuboCop that supports `--format github` we can drop it, or introduce a parameter to override it.

**Review by ekohl — APPROVED** [review]
This was introduced in https://github.com/rubocop/rubocop/commit/1551c24c78a2b5a3b4bb143aba21ea97ef22fe70, so RuboCop 0.47.0. I think it's safe to assume that's used everywhere now.

**Comment by evgeni** [comment]
Well, the slowness comes mostly from missing `--parallel`, not Rails, but passing `--parallel` in the rake variant is not officially supported.

https://github.com/rubocop/rubocop/issues/5942
https://github.com/rubocop/rubocop/issues/6495

**Comment by ekohl** [comment]
I also noticed that rake is faster than the non-parallel once, which is surprising.

**Pull request merged**
