### PR TITLE
Create a tag when version.rb is changed

### PR DESCRIPTION
**Pull request by stejskalleos**

### CODE REVIEW

**Comment by stejskalleos** [comment]
With this action + gem publishing, releasing plugins can be a little bit easier, see the PR for foreman_ansible: https://github.com/theforeman/foreman_ansible/pull/686

**Comment by stejskalleos** [comment]
@ekohl @evgeni can you please take a look at the PR?
Would be nice to have it in our plugin stack, we release new stuff quite often.

**Comment by evgeni** [comment]
I personally find this is the wrong trigger for a release.

Sometimes
* the version is bumped without a release (e.g. to indicate that the next release will be a major: https://github.com/theforeman/foreman_ansible/commit/2802b7664396fe3cff675d498f107df47f94d8dd)
* people bump versions directly after release/branching to indicate the next version (https://github.com/Katello/katello/commit/890c5e2d51210634201ddaf2e7dbab2776905250)
* version.rb is edited because of a linter (https://github.com/theforeman/foreman_ansible/commit/49055ab0e2c93c4272879944a1a3c63b03b35c87#diff-e05c7f8820246568109bfe64608aea39404b500d8858e8944b453a82e44e9694)

On the other hand, pushing a tag is a conscious decision taken by a developer, which sounds like a much better trigger to start the release train (plus, it could be limited to signed tags, so we actually know what we release)

I obviously can't tell you what to do in your repos, but I'd prefer not to have this as a "recommended approach".

**Comment by stejskalleos** [comment]
@evgeni Good points, I didn't realize that version could be edited without the necessary release of the gem.

So what if the workflow would be `on: workflow_dispatch`?

* Admin will run the _Release gem_  job manually
* Tag will be created
* Gem release will be triggered by the created tag

**Comment by evgeni** [comment]
Sure, this could be a `on: workflow_dispatch`, but that means that someone needs to
- bump the version in the right branch
- go to the GitHub Actions UI and call the workflow (telling it which branch to use)

and then I don't see the time saving benefit of having that instead of
- bump the version in the right branch
- `git tag v<X> && git push origin v<X>` (we could even have a `rake release` that figures out `<X>` automatically and performs tagging/pushing)

(This is what everyone uses today via https://github.com/theforeman/actions/?tab=readme-ov-file#gem-release)

**Comment by evgeni** [comment]
FWIW, over in @voxpupuli, we have this gem in our rake tasks:
https://github.com/voxpupuli/voxpupuli-release/blob/52377db498ec9418fa0100d47bd2226ca22cd60b/lib/voxpupuli/release/rake_tasks.rb#L46-L80

It does a bit more (like validation and post-release-version-bump (!)) but the gist is "bump the version, call `rake release`, done"

**Comment by evgeni** [comment]
@stejskalleos can we close this one then?

**Comment by ekohl** [comment]
FYI there is a set of release tasks in bundler itself that can create a tag and push a release. I din't use them often, but it can be used

**Pull request closed without merging**
